name: aloha
dependencies:
  - python=3.8.10
  - pip=24.0
  - pip:
    - torchvision
    - torch
    - pyquaternion
    - pyyaml
    - rospkg
    - pexpect
    - mujoco==2.3.7
    - dm_control==1.0.14
    - opencv-python
    - matplotlib
    - einops
    - packaging
    - h5py
    - ipython
    - modern_robotics
